import * as stylex from '@stylexjs/stylex'
import { shadow, space } from '@/lib/constants.stylex'
import { colors, radius } from '@/lib/tokens.stylex'

export const paddingStyles = stylex.create({
  none: { padding: space.none },
  '2xs': { padding: space['2xs'] },
  xs: { padding: space.xs },
  fine: { padding: space.fine },
  sm: { padding: space.sm },
  sm2: { padding: space.sm2 },
  md: { padding: space.md },
  lg: { padding: space.lg },
  xl: { padding: space.xl },
  '2xl': { padding: space['2xl'] },
  '3xl': { padding: space['3xl'] },
  '4xl': { padding: space['4xl'] },
  '5xl': { padding: space['5xl'] },
  '6xl': { padding: space['6xl'] },
  '7xl': { padding: space['7xl'] },
})

export const paddingInlineStyles = stylex.create({
  none: { paddingInline: space.none },
  '2xs': { paddingInline: space['2xs'] },
  xs: { paddingInline: space.xs },
  fine: { paddingInline: space.fine },
  sm: { paddingInline: space.sm },
  sm2: { paddingInline: space.sm2 },
  md: { paddingInline: space.md },
  lg: { paddingInline: space.lg },
  xl: { paddingInline: space.xl },
  '2xl': { paddingInline: space['2xl'] },
  '3xl': { paddingInline: space['3xl'] },
  '4xl': { paddingInline: space['4xl'] },
  '5xl': { paddingInline: space['5xl'] },
  '6xl': { paddingInline: space['6xl'] },
  '7xl': { paddingInline: space['7xl'] },
})

export const paddingBlockStyles = stylex.create({
  none: { paddingBlock: space.none },
  '2xs': { paddingBlock: space['2xs'] },
  xs: { paddingBlock: space.xs },
  fine: { paddingBlock: space.fine },
  sm: { paddingBlock: space.sm },
  sm2: { paddingBlock: space.sm2 },
  md: { paddingBlock: space.md },
  lg: { paddingBlock: space.lg },
  xl: { paddingBlock: space.xl },
  '2xl': { paddingBlock: space['2xl'] },
  '3xl': { paddingBlock: space['3xl'] },
  '4xl': { paddingBlock: space['4xl'] },
  '5xl': { paddingBlock: space['5xl'] },
  '6xl': { paddingBlock: space['6xl'] },
  '7xl': { paddingBlock: space['7xl'] },
})

export const marginStyles = stylex.create({
  none: { margin: space.none },
  '2xs': { margin: space['2xs'] },
  xs: { margin: space.xs },
  fine: { margin: space.fine },
  sm: { margin: space.sm },
  sm2: { margin: space.sm2 },
  md: { margin: space.md },
  lg: { margin: space.lg },
  xl: { margin: space.xl },
  '2xl': { margin: space['2xl'] },
  '3xl': { margin: space['3xl'] },
  '4xl': { margin: space['4xl'] },
  '5xl': { margin: space['5xl'] },
  '6xl': { margin: space['6xl'] },
  '7xl': { margin: space['7xl'] },
  '-2xs': { margin: `calc(${space['2xs']} * -1)` },
  '-xs': { margin: `calc(${space.xs} * -1)` },
  '-fine': { margin: `calc(${space.fine} * -1)` },
  '-sm': { margin: `calc(${space.sm} * -1)` },
  '-sm2': { margin: `calc(${space.sm2} * -1)` },
  '-md': { margin: `calc(${space.md} * -1)` },
  '-lg': { margin: `calc(${space.lg} * -1)` },
  '-xl': { margin: `calc(${space.xl} * -1)` },
  '-2xl': { margin: `calc(${space['2xl']} * -1)` },
  '-3xl': { margin: `calc(${space['3xl']} * -1)` },
  '-4xl': { margin: `calc(${space['4xl']} * -1)` },
  '-5xl': { margin: `calc(${space['5xl']} * -1)` },
  '-6xl': { margin: `calc(${space['6xl']} * -1)` },
  '-7xl': { margin: `calc(${space['7xl']} * -1)` },
  auto: { margin: 'auto' },
})

export const marginInlineStyles = stylex.create({
  none: { marginInline: space.none },
  '2xs': { marginInline: space['2xs'] },
  xs: { marginInline: space.xs },
  fine: { marginInline: space.fine },
  sm: { marginInline: space.sm },
  sm2: { marginInline: space.sm2 },
  md: { marginInline: space.md },
  lg: { marginInline: space.lg },
  xl: { marginInline: space.xl },
  '2xl': { marginInline: space['2xl'] },
  '3xl': { marginInline: space['3xl'] },
  '4xl': { marginInline: space['4xl'] },
  '5xl': { marginInline: space['5xl'] },
  '6xl': { marginInline: space['6xl'] },
  '7xl': { marginInline: space['7xl'] },
  '-2xs': { marginInline: `calc(${space['2xs']} * -1)` },
  '-xs': { marginInline: `calc(${space.xs} * -1)` },
  '-fine': { marginInline: `calc(${space.fine} * -1)` },
  '-sm': { marginInline: `calc(${space.sm} * -1)` },
  '-sm2': { marginInline: `calc(${space.sm2} * -1)` },
  '-md': { marginInline: `calc(${space.md} * -1)` },
  '-lg': { marginInline: `calc(${space.lg} * -1)` },
  '-xl': { marginInline: `calc(${space.xl} * -1)` },
  '-2xl': { marginInline: `calc(${space['2xl']} * -1)` },
  '-3xl': { marginInline: `calc(${space['3xl']} * -1)` },
  '-4xl': { marginInline: `calc(${space['4xl']} * -1)` },
  '-5xl': { marginInline: `calc(${space['5xl']} * -1)` },
  '-6xl': { marginInline: `calc(${space['6xl']} * -1)` },
  '-7xl': { marginInline: `calc(${space['7xl']} * -1)` },
  auto: { marginInline: 'auto' },
})

export const marginBlockStyles = stylex.create({
  none: { marginBlock: space.none },
  '2xs': { marginBlock: space['2xs'] },
  xs: { marginBlock: space.xs },
  fine: { marginBlock: space.fine },
  sm: { marginBlock: space.sm },
  sm2: { marginBlock: space.sm2 },
  md: { marginBlock: space.md },
  lg: { marginBlock: space.lg },
  xl: { marginBlock: space.xl },
  '2xl': { marginBlock: space['2xl'] },
  '3xl': { marginBlock: space['3xl'] },
  '4xl': { marginBlock: space['4xl'] },
  '5xl': { marginBlock: space['5xl'] },
  '6xl': { marginBlock: space['6xl'] },
  '7xl': { marginBlock: space['7xl'] },
  '-2xs': { marginBlock: `calc(${space['2xs']} * -1)` },
  '-xs': { marginBlock: `calc(${space.xs} * -1)` },
  '-fine': { marginBlock: `calc(${space.fine} * -1)` },
  '-sm': { marginBlock: `calc(${space.sm} * -1)` },
  '-sm2': { marginBlock: `calc(${space.sm2} * -1)` },
  '-md': { marginBlock: `calc(${space.md} * -1)` },
  '-lg': { marginBlock: `calc(${space.lg} * -1)` },
  '-xl': { marginBlock: `calc(${space.xl} * -1)` },
  '-2xl': { marginBlock: `calc(${space['2xl']} * -1)` },
  '-3xl': { marginBlock: `calc(${space['3xl']} * -1)` },
  '-4xl': { marginBlock: `calc(${space['4xl']} * -1)` },
  '-5xl': { marginBlock: `calc(${space['5xl']} * -1)` },
  '-6xl': { marginBlock: `calc(${space['6xl']} * -1)` },
  '-7xl': { marginBlock: `calc(${space['7xl']} * -1)` },
  auto: { marginBlock: 'auto' },
})

export const gapStyles = stylex.create({
  none: { gap: space.none },
  '2xs': { gap: space['2xs'] },
  xs: { gap: space.xs },
  fine: { gap: space.fine },
  sm: { gap: space.sm },
  sm2: { gap: space.sm2 },
  md: { gap: space.md },
  lg: { gap: space.lg },
  xl: { gap: space.xl },
  '2xl': { gap: space['2xl'] },
  '3xl': { gap: space['3xl'] },
  '4xl': { gap: space['4xl'] },
  '5xl': { gap: space['5xl'] },
  '6xl': { gap: space['6xl'] },
  '7xl': { gap: space['7xl'] },
})

export const rowGapStyles = stylex.create({
  none: { rowGap: space.none },
  '2xs': { rowGap: space['2xs'] },
  xs: { rowGap: space.xs },
  fine: { rowGap: space.fine },
  sm: { rowGap: space.sm },
  sm2: { rowGap: space.sm2 },
  md: { rowGap: space.md },
  lg: { rowGap: space.lg },
  xl: { rowGap: space.xl },
  '2xl': { rowGap: space['2xl'] },
  '3xl': { rowGap: space['3xl'] },
  '4xl': { rowGap: space['4xl'] },
  '5xl': { rowGap: space['5xl'] },
  '6xl': { rowGap: space['6xl'] },
  '7xl': { rowGap: space['7xl'] },
})

export const columnGapStyles = stylex.create({
  none: { columnGap: space.none },
  '2xs': { columnGap: space['2xs'] },
  xs: { columnGap: space.xs },
  fine: { columnGap: space.fine },
  sm: { columnGap: space.sm },
  sm2: { columnGap: space.sm2 },
  md: { columnGap: space.md },
  lg: { columnGap: space.lg },
  xl: { columnGap: space.xl },
  '2xl': { columnGap: space['2xl'] },
  '3xl': { columnGap: space['3xl'] },
  '4xl': { columnGap: space['4xl'] },
  '5xl': { columnGap: space['5xl'] },
  '6xl': { columnGap: space['6xl'] },
  '7xl': { columnGap: space['7xl'] },
})

export const backgroundColorStyles = stylex.create({
  accent: { backgroundColor: colors.accent },
  accentForeground: { backgroundColor: colors.accentForeground },
  background: { backgroundColor: colors.background },
  border: { backgroundColor: colors.border },
  card: { backgroundColor: colors.card },
  cardForeground: { backgroundColor: colors.cardForeground },
  destructive: { backgroundColor: colors.destructive },
  destructiveForeground: { backgroundColor: colors.destructiveForeground },
  foreground: { backgroundColor: colors.foreground },
  input: { backgroundColor: colors.input },
  muted: { backgroundColor: colors.muted },
  mutedForeground: { backgroundColor: colors.mutedForeground },
  popover: { backgroundColor: colors.popover },
  popoverForeground: { backgroundColor: colors.popoverForeground },
  primary: { backgroundColor: colors.primary },
  primaryForeground: { backgroundColor: colors.primaryForeground },
  ring: { backgroundColor: colors.ring },
  secondary: { backgroundColor: colors.secondary },
  secondaryForeground: { backgroundColor: colors.secondaryForeground },
  sidebar: { backgroundColor: colors.sidebar },
  sidebarAccent: { backgroundColor: colors.sidebarAccent },
  sidebarAccentForeground: { backgroundColor: colors.sidebarAccentForeground },
  sidebarBorder: { backgroundColor: colors.sidebarBorder },
  sidebarForeground: { backgroundColor: colors.sidebarForeground },
  sidebarPrimary: { backgroundColor: colors.sidebarPrimary },
  sidebarPrimaryForeground: { backgroundColor: colors.sidebarPrimaryForeground },
  sidebarRing: { backgroundColor: colors.sidebarRing },
  codeBackground: { backgroundColor: colors.codeBackground },
  codeForeground: { backgroundColor: colors.codeForeground },
  overlayScrim: { backgroundColor: colors.overlayScrim },
  proseBody: { backgroundColor: colors.proseBody },
  proseHeading: { backgroundColor: colors.proseHeading },
})

export const colorStyles = stylex.create({
  accent: { color: colors.accent },
  accentForeground: { color: colors.accentForeground },
  background: { color: colors.background },
  border: { color: colors.border },
  card: { color: colors.card },
  cardForeground: { color: colors.cardForeground },
  destructive: { color: colors.destructive },
  destructiveForeground: { color: colors.destructiveForeground },
  foreground: { color: colors.foreground },
  input: { color: colors.input },
  muted: { color: colors.muted },
  mutedForeground: { color: colors.mutedForeground },
  popover: { color: colors.popover },
  popoverForeground: { color: colors.popoverForeground },
  primary: { color: colors.primary },
  primaryForeground: { color: colors.primaryForeground },
  ring: { color: colors.ring },
  secondary: { color: colors.secondary },
  secondaryForeground: { color: colors.secondaryForeground },
  sidebar: { color: colors.sidebar },
  sidebarAccent: { color: colors.sidebarAccent },
  sidebarAccentForeground: { color: colors.sidebarAccentForeground },
  sidebarBorder: { color: colors.sidebarBorder },
  sidebarForeground: { color: colors.sidebarForeground },
  sidebarPrimary: { color: colors.sidebarPrimary },
  sidebarPrimaryForeground: { color: colors.sidebarPrimaryForeground },
  sidebarRing: { color: colors.sidebarRing },
  codeBackground: { color: colors.codeBackground },
  codeForeground: { color: colors.codeForeground },
  overlayScrim: { color: colors.overlayScrim },
  proseBody: { color: colors.proseBody },
  proseHeading: { color: colors.proseHeading },
})

export const borderColorStyles = stylex.create({
  accent: { borderColor: colors.accent },
  accentForeground: { borderColor: colors.accentForeground },
  background: { borderColor: colors.background },
  border: { borderColor: colors.border },
  card: { borderColor: colors.card },
  cardForeground: { borderColor: colors.cardForeground },
  destructive: { borderColor: colors.destructive },
  destructiveForeground: { borderColor: colors.destructiveForeground },
  foreground: { borderColor: colors.foreground },
  input: { borderColor: colors.input },
  muted: { borderColor: colors.muted },
  mutedForeground: { borderColor: colors.mutedForeground },
  popover: { borderColor: colors.popover },
  popoverForeground: { borderColor: colors.popoverForeground },
  primary: { borderColor: colors.primary },
  primaryForeground: { borderColor: colors.primaryForeground },
  ring: { borderColor: colors.ring },
  secondary: { borderColor: colors.secondary },
  secondaryForeground: { borderColor: colors.secondaryForeground },
  sidebar: { borderColor: colors.sidebar },
  sidebarAccent: { borderColor: colors.sidebarAccent },
  sidebarAccentForeground: { borderColor: colors.sidebarAccentForeground },
  sidebarBorder: { borderColor: colors.sidebarBorder },
  sidebarForeground: { borderColor: colors.sidebarForeground },
  sidebarPrimary: { borderColor: colors.sidebarPrimary },
  sidebarPrimaryForeground: { borderColor: colors.sidebarPrimaryForeground },
  sidebarRing: { borderColor: colors.sidebarRing },
  codeBackground: { borderColor: colors.codeBackground },
  codeForeground: { borderColor: colors.codeForeground },
  overlayScrim: { borderColor: colors.overlayScrim },
  proseBody: { borderColor: colors.proseBody },
  proseHeading: { borderColor: colors.proseHeading },
})

export const borderRadiusStyles = stylex.create({
  none: { borderRadius: radius.none },
  xs: { borderRadius: radius.xs },
  sm: { borderRadius: radius.sm },
  md: { borderRadius: radius.md },
  lg: { borderRadius: radius.lg },
  xl: { borderRadius: radius.xl },
  full: { borderRadius: radius.full },
})

export const boxShadowStyles = stylex.create({
  none: { boxShadow: shadow.none },
  sm: { boxShadow: shadow.sm },
  lg: { boxShadow: shadow.lg },
})

export const displayStyles = stylex.create({
  block: { display: 'block' },
  flex: { display: 'flex' },
  inline: { display: 'inline' },
  'inline-flex': { display: 'inline-flex' },
  grid: { display: 'grid' },
  none: { display: 'none' },
  contents: { display: 'contents' },
})

export const flexDirectionStyles = stylex.create({
  row: { flexDirection: 'row' },
  column: { flexDirection: 'column' },
  'row-reverse': { flexDirection: 'row-reverse' },
  'column-reverse': { flexDirection: 'column-reverse' },
})

export const flexWrapStyles = stylex.create({
  wrap: { flexWrap: 'wrap' },
  nowrap: { flexWrap: 'nowrap' },
  'wrap-reverse': { flexWrap: 'wrap-reverse' },
})

export const flexStyles = stylex.create({
  '1': { flex: '1' },
  none: { flex: 'none' },
  auto: { flex: 'auto' },
})

export const alignItemsStyles = stylex.create({
  start: { alignItems: 'start' },
  end: { alignItems: 'end' },
  center: { alignItems: 'center' },
  baseline: { alignItems: 'baseline' },
  stretch: { alignItems: 'stretch' },
})

export const justifyContentStyles = stylex.create({
  start: { justifyContent: 'start' },
  end: { justifyContent: 'end' },
  center: { justifyContent: 'center' },
  between: { justifyContent: 'space-between' },
  around: { justifyContent: 'space-around' },
  evenly: { justifyContent: 'space-evenly' },
})

export const borderWidthStyles = stylex.create({
  '0': { borderWidth: '0' },
  '1': { borderWidth: '1px' },
})

export const borderStyleStyles = stylex.create({
  solid: { borderStyle: 'solid' },
  dashed: { borderStyle: 'dashed' },
  dotted: { borderStyle: 'dotted' },
  none: { borderStyle: 'none' },
})

export const widthStyles = stylex.create({
  full: { width: '100%' },
})
